Repository Arquisoft/radarin_en2a, pull requests merged in 2021-04, with the labels that each got.

#108 Image added
  webapp/docs/images/03_System_scope_and_context.png
Labels: documentation

#113 Alonso get friends near
  restapi/services/UsersService.js
Labels: implementation

#117 Doc changes
  webapp/docs/01_introduction_and_goals.adoc
  webapp/docs/03_system_scope_and_context.adoc
  webapp/docs/04_solution_strategy.adoc
  webapp/docs/05_building_block_view.adoc
  webapp/docs/06_runtime_view.adoc
  webapp/docs/07_deployment_view.adoc
  webapp/docs/images/05_deployment_view_2.png
  webapp/docs/images/07_deployment_view.jpg
  webapp/docs/images/07_deployment_view.png
Labels: documentation, enhancement

#132 Alonso docs notifications
  webapp/docs/05_building_block_view.adoc
  webapp/docs/06_runtime_view.adoc
  webapp/package-lock.json
Labels: documentation, enhancement
